title:              끄적끄적
email:              rachel9414@gmail.com
description:        Studying to be a Data Scientist
author:             kkeujeogx2
baseurl:            ""
url:                "https://Kkeujeog.github.io"

# Social Profiles
github_username:    Kkeujeog
facebook_username:  Jungseo Mun
instagram_username: moon_emotion

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
